---
title: "Learn More About Me"
---

I am an accomplished data professional with over five years of experience working with data in industry. I am passionate about delivering actionable analytical insights that inform and drive improved policy and outcomes. I have worked with all stages of the analysis process including synthesizing research questions from business requirements, extracting and cleaning complex administrative data, conducting statistical analysis and modelling, and presenting results in an easily comprehensible format. 

You can look at the code for my personal projects at [GitHub](https://github.com/Gippers>).

I am contactable at <thomas.martin.stats@gmail.com>.

## Education

**Masters of Statistics**

- Australian National University
- March 2023 – Ongoing

**Graduate Certificate of Finance and Actuarial Statistics**

- Australian National University 
- March 2023 – Dec 2024

**Bachelor of Science**

- Major in Computer Science and Minor in Mathematics
- Australian National University/University of New South Wales
- March 2015 - November 2018



## Professional Experience

Over 5 years industry experience working in the data analytics/science sector. Some of the tasks I have under taken include; building BI tools, wrangling data, performing data modelling including regression modelling and forecasting, and collating these results into reports.
